version: '3'

services:

  frontend:
    build: .
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/home/node/app

  backend:
    build: .
    ports:
      - 3002:3333
      - 5555:5555
    volumes:
      - ./backend:/home/node/app