version: '3'

services:

  frontend:
    build: .
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/home/node/app

  backend:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./backend:/home/node/app